version: "3.8"

services:
  monolith:
    build:
      context: .
      dockerfile: php.monolith.Dockerfile
      args:
        - IMAGE_TAG=${PHP_IMAGE_TAG}
    container_name: fma_monolith_php
    volumes:
      - ./app:/var/www/html:rw

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
      args:
        - IMAGE_TAG=${RABBIT_MQ_IMAGE_TAG}
    ports:
      - ${RABBIT_MQ_ADMIN_PANEL_EXTERNAL_PORT}:15672
    container_name: fma_rabbit_mq

  datahub-write-test:
    build:
      context: .
      dockerfile: datahub.write.test.Dockerfile
      args:
        - IMAGE_TAG=${GOLANG_IMAGE_TAG}
    container_name: fma_datahub_write_test

  datahub-write:
    build:
      context: .
      dockerfile: datahub.write.Dockerfile
      args:
        - IMAGE_TAG=${GOLANG_IMAGE_TAG}
    volumes:
      - ./datahub/write:/src:rw
    container_name: fma_datahub_write
    depends_on:
      - datahub-write-test
