parameters:
  app.clock.timezone: '%env(resolve: APP_TIMEZONE)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  App\Core\Shared\Infrastructure\Clock\PsrClock:
    factory: [ 'App\Core\Shared\Infrastructure\Clock\PsrClockFactory', 'create' ]
    arguments:
      $timezone: '%app.clock.timezone%'