name: PHP Composer

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --check-lock --working-dir=./app

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Create .env file
        run: touch ./app/.env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=./app

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --check-lock --working-dir=./app

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Create .env file
        run: touch ./app/.env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=./app

      - name: Run PHPUnit
        run: composer run-script run-tests --working-dir=./app

  phpstan:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --check-lock --working-dir=./app

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Create .env file
        run: touch ./app/.env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=./app

      - name: Run PHP Stan
        run: composer run-script run-phpstan --working-dir=./app

  phpcs:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --check-lock --working-dir=./app

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Create .env file
        run: touch ./app/.env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=./app

      - name: Run PHP CodeSniffer
        run: composer run-script run-phpcs --working-dir=./app
